---
- name: Dotfiles Setup
  block:
    - name: Clone Oh My Zsh
      ansible.builtin.git:
        repo: "{{ base_zsh_url }}"
        dest: /home/{{ ansible_user }}/.oh-my-zsh
        single_branch: true
        version: master

    - name: Copy dotfiles
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/{{ ansible_user }}/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      with_fileglob:
        - "files/configs/.*"
