version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
    commit-message:
      prefix: "actions: "
      include: "scope"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "python"
      - "dependencies"
    groups:
      updates:
        applies-to: "version-updates"
        update-types: 
          - "minor"
      security:
        applies-to: "security-updates"
        update-types: 
          - "minor"
    commit-message:
      prefix: "pip: "
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
