version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
    commit-message:
      prefix: "actions: "
      include: "scope"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      upgrades:
        applies-to: "version-updates"
        update-types: 
          - "minor"
        labels:
          - "python"
          - "dependencies"
    commit-message:
      prefix: "pip: "
      include: "scope"
