---
collections:
  - community.crypto
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.2.0
  - community.docker
    # https://docs.ansible.com/ansible/latest/collections/community/docker/docsite/scenario_guide.html#
  - kubernetes.core
    # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/index.html
