---
vagrant:
  children:
    vagrant_control:
      hosts:
        vagrant-plane01.local:
        vagrant-plane02.local:
    vagrant_nodes:
      hosts:
        vagrant-w01.local:
        vagrant-w02.local:

kube_control_plane:
  children:
    vagrant_control:

etcd:
  children:
    vagrant_control:

kube_nodes:
  children:
    vagrant_nodes:

k8s_cluster:
  children:
    kube_control_plane:
    kube_nodes:
