---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: grafana
  name: grafana
spec:
  containers:
  - image: grafana/grafana
    name: grafana
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
      requests:
        memory: "100Mi"
        cpu: "0.5"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  automountServiceAccountToken: false
status: {}
