name: Check python code
on:
  push:
    paths:
      - "ansible/callback_plugins/**"

env:
  FORCE_COLOR: 1

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: pip3 install asn1crypto atheris pytype ruff
    - name: Run ruff checks
      run: ruff check src
    - name: Run pytype checks
      run: pytype src
