name: Lint Ansible code
on:
  push:
    paths:
      - "ansible/**"

permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
